"use strict";
(() => {
const $=id=>document.getElementById(id),API="https://api.scriptnovaa.com/api/property-security";let pairing=null,stream=null,pc=null,running=false,generation="",wake=null,busy=false,run=0;
const initial=location.hash.slice(1);history.replaceState(null,"",location.pathname);$("pair").value=initial;
function decode(value){const text=value.includes("#")?value.split("#").pop():value;const p=JSON.parse(decodeURIComponent(escape(atob(text))));if(!/^[a-z0-9-]{1,48}$/.test(p.id)||!p.token||!Array.isArray(p.iceServers))throw Error("Use the pairing link from your dashboard.");return p;}
async function request(path,body){const r=await fetch(API+path,{method:body?"POST":"GET",headers:{Authorization:"Bearer "+pairing.token,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok)throw Error(j.error||"Connection request failed.");return j;}
function stop(){run++;running=false;pc?.close();pc=null;stream?.getTracks().forEach(t=>t.stop());stream=null;$("preview").srcObject=null;generation="";wake?.release().catch(()=>{});wake=null;$("status").textContent="Camera off";$("start").disabled=false;}
async function start(){stop();const current=run;$("start").disabled=true;try{pairing=decode($("pair").value);$("name").textContent=pairing.name+" · "+pairing.location;const device=$("device").value;const captured=await navigator.mediaDevices.getUserMedia({audio:false,video:{width:{ideal:640},height:{ideal:360},frameRate:{ideal:15,max:20},...(device?{deviceId:{exact:device}}:{facingMode:{ideal:"environment"}})}});if(current!==run){captured.getTracks().forEach(t=>t.stop());return;}stream=captured;$("preview").srcObject=stream;await $("preview").play();const devices=await navigator.mediaDevices.enumerateDevices();$("device").replaceChildren(new Option("Rear camera (default)",""));for(const d of devices.filter(d=>d.kind==="videoinput"))$("device").add(new Option(d.label||"Camera",d.deviceId));$("device").value=device;running=true;$("status").textContent="Camera ready · Press Connect / reconnect on the dashboard";try{wake=await navigator.wakeLock?.request("screen");}catch{}stream.getVideoTracks()[0].onended=()=>{stop();$("status").textContent="Camera capture interrupted. Unlock the phone and start again.";};}catch(e){stop();$("status").textContent=e.message;}}
async function gather(peer){await new Promise(resolve=>{if(peer.iceGatheringState==="complete")return resolve();const timer=setTimeout(done,10000);function done(){clearTimeout(timer);peer.removeEventListener("icegatheringstatechange",check);resolve();}function check(){if(peer.iceGatheringState==="complete")done();}peer.addEventListener("icegatheringstatechange",check);});}
async function poll(){if(!running||busy)return;busy=true;const current=run;try{const j=await request("/signal/"+pairing.id);if(current!==run||!running)return;const s=j.signal;if(s?.offer&&s.generation!==generation){pc?.close();const peer=new RTCPeerConnection({iceServers:pairing.iceServers});pc=peer;generation=s.generation;for(const t of stream.getTracks())peer.addTrack(t,stream);peer.onconnectionstatechange=()=>{if(pc===peer)$("status").textContent=peer.connectionState==="connected"?"Live · Sending video to PC":"Connection: "+peer.connectionState;};await peer.setRemoteDescription(s.offer);await peer.setLocalDescription(await peer.createAnswer());await gather(peer);if(current!==run||pc!==peer)return;await request("/signal/"+pairing.id,{generation:s.generation,description:peer.localDescription.toJSON()});}}catch(e){if(current===run){generation="";$("status").textContent=e.message;}}finally{busy=false;}}
$("start").onclick=start;$("stop").onclick=stop;$("device").onchange=()=>{if(running)start();};setInterval(poll,1800);window.addEventListener("pagehide",stop);document.addEventListener("visibilitychange",()=>{if(document.hidden&&running)$("status").textContent="Safari may pause video while hidden. Keep this page visible.";});
})();
